development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:653046d9694d7649cf5ec2d71996b4e1@pike.redistogo.com:9771/
  channel_prefix: backend_production
