development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:fd6d416f229451eaa9a411684ee2b6f8@pike.redistogo.com:9951/
  channel_prefix: backend_production
